=begin

WELCOME THE USER

ASK IF THE USER HAS A TABLE CONFIGURATION

WE WANT TO FIND OUT HOW MANY TABLES ARE IN RESTRAUNT ( TABLE-TERMINAL)

HOW MANY SEATS AT THE TABLE ( TESTING WILL START AT 4 AND POSSIBLY INCREASE BASED ON TIME)


HOW MANY STAFF ON DUTY?

ASSIGN TABLES TO STAFF

WHILE LOOP CALLED OPERATING HOURS

    WHO'S THERE? 

        ARE THERE ANY DIETRY REQUIREMENTS? ( FAKER)

        WHAT TABLE IS THE CUSTOMER AT?

        CUSTOMER ORDER

            ADD ORDER

            MODIFY ORDER

            CUSTOMER ORDER PLUS TOTAL

        HAS THE CUSTOMER PAID

    NEW CUSTOMER (POSSIBLY A WHILE LOOP ON THIS LOOP SO FRONT DESK DOESNT LOSE USER INFO)

        ANY DIETRY REQUIREMENTS

        WHAT TABLE WILL THEY BE ASSIGNED




    ORDER INFO

        WHAT FOOD'S BEEN ORDERED? ( WHAT FOOD HAS BEEN TAKEN OUT? CAN BE DONE USING COLORIZE) ( ???ANY DELAYS ON FOOD???)

        ORDER SENT



    TABLES IN USE ( EG NUMBER OF SEATS PER TABLE USED)




    END OF SERVICE



END OF NIGHT 

WHAT WAS SOLD

HOW MANY CUSTOMERS

ITEMS TOTAL COST

HOW MUCH MONEY MADE

TIPS MADE

NIGHTS LAYOUT BY TIME

=end