=begin

(ORGANISATION) WELCOME THE USER 

(ORGANISATION) ASK IF THE USER HAS A TABLE CONFIGURATION 

(ORGANISATION) WE WANT TO FIND OUT HOW MANY TABLES ARE IN RESTRAUNT ( TABLE-TERMINAL) 

(ORGANISATION) HOW MANY SEATS AT THE TABLE ( TESTING WILL START AT 4 AND POSSIBLY INCREASE BASED ON TIME)


(ORGANISATION) HOW MANY STAFF ON DUTY?

(ORGANISATION) ASSIGN TABLES TO STAFF

(OPERATIONS) WHILE LOOP CALLED OPERATING HOURS

    (CUSTOMER) WHO'S THERE? 

        (CUSTOMER) ARE THERE ANY DIETRY REQUIREMENTS? ( FAKER)

        (CUSTOMER) WHAT TABLE IS THE CUSTOMER AT?

        (CUSTOMER) CUSTOMER ORDER

            (CUSTOMER) ADD ORDER

            (CUSTOMER) MODIFY ORDER

            (CUSTOMER) CUSTOMER ORDER PLUS TOTAL

        (CUSTOMER) HAS THE CUSTOMER PAID

    (NEW_CUST) NEW CUSTOMER (POSSIBLY A WHILE LOOP ON THIS LOOP SO FRONT DESK DOESNT LOSE USER INFO)

        (NEW_CUST) ENTER CUSTOMER NAME

        (NEW_CUST) ANY DIETRY REQUIREMENTS

        (NEW_CUST) WHAT TABLE WILL THEY BE ASSIGNED




    (ORDER) ORDER INFO

        (ORDER) WHAT FOOD'S BEEN ORDERED? ( WHAT FOOD HAS BEEN TAKEN OUT? CAN BE DONE USING COLORIZE) ( ???ANY DELAYS ON FOOD???)

        (ORDER) TABLES IN USE ( EG NUMBER OF SEATS PER TABLE USED)

        (ORDER) ORDER SENT



    (OPERATIONS) END OF SERVICE



(OPERATIONS) END OF NIGHT 

(CLOSING) WHAT WAS SOLD

(CLOSING) HOW MANY CUSTOMERS

(CLOSING) ITEMS TOTAL COST

(CLOSING) HOW MUCH MONEY MADE

(CLOSING) TIPS MADE

(CLOSING) NIGHTS LAYOUT BY TIME

=end